# For more information: https://laravel.com/docs/sail
version: '3'
services:
#  laravel.test:
#    build:
#      context: ./vendor/laravel/sail/runtimes/8.2
#      dockerfile: ./vendor/laravel/sail/runtimes/8.2/Dockerfile
#      args:
#        WWWGROUP: '${WWWGROUP}'
#    image: sail-8.2/app
#    extra_hosts:
#      - 'host.docker.internal:host-gateway'
##    ports:
##      - '${APP_PORT:-80}:80'
##      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
#    expose:
#      - 80
#      - 5173
#    environment:
#      WWWUSER: '${WWWUSER}'
#      LARAVEL_SAIL: 1
#      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
#      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
#    volumes:
#      - './../laravel:/var/www/html'
#      - './:/opt/packages/antidote/laravel-form'
#    networks:
#      - sail
  mariadb:
    image: 'mariadb:10'
#    ports:
#      - '${FORWARD_DB_PORT:-3306}:3306'
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'new'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  test.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: ./vendor/laravel/sail/runtimes/8.2/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
#    ports:
#      - '${APP_PORT:-80}:80'
#      - '${VITE_PORT:-5174}:${VITE_PORT:-5174}'
    expose:
      - 80
      - 5174
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-develop,debug,coverage}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - './:/var/www/html'
    networks:
      - sail
  mailpit:
    image: 'axllent/mailpit:latest'
#    ports:
#      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
#      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    expose:
      - 1025
      - 8025
    networks:
      - sail
  redis:
    image: 'redis:alpine'
#    ports:
#      - '${FORWARD_REDIS_PORT:-6379}:6379'
    expose:
      - 6379
#    volumes:
#      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
    sail-mariadb:
      driver: local